config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
    @group = ['Beyonce', 'Kelly']
    if params[:member]
      @group = @group.select { |member| member == params[:member] }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <span>Navbar here</span>
      <%= link_to 'Home', root_path %>
      <%= link_to 'About', about_path %>
      <%= link_to 'Contact', contact_path %>
    </div>

    <%= yield %>

    <div>
    <span>Footer here</span>

    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>First Rails App</h1>

<%#= Time.now %>

app/views/pages/contact.html.erb
<h1>These are the contacts</h1>

<%#= Time.now %>
<%#group = ['Beyonce', 'Kelly'] %>
<%# you could use it like the line above but better to add the group instance to the controller %>

<form action="/contact" method="get">
  <input type="text" name="member" placeholder="Who are you looking for?">
  <input type="submit">
</form>

<ul>
<% @group.each do |member| %>
  <li><%= member %></li>
<% end %>
</ul>

app/views/pages/home.html.erb
<h1> The home page! </h1>